### ISSUE TITLE
Bug Report: Controls option's buggy asf

### ISSUE THREAD

**Issue by Sanscode1937** [AngelDTF/FNF-NewgroundsPort#11]
![image](https://user-images.githubusercontent.com/88786260/150676466-d2126b56-5e18-4adb-b57f-7a8db7c138f9.png)

**Comment by AngelWyvern** [comment]
This is just a visual bug that happens in the controls menu for some reason. If you close the options menu and reopen it, then go back into controls, the text will reset back to the assigned inputs. I'm already working on a fix for this as I've been slowly rechecking all of my work on the UI files.

**Comment by AngelWyvern** [comment]
Fixed in commit a86fc9776f22a3b7fd8be52e5aeab902bba7c161
