### ISSUE TITLE
Enhancement: Pretty print fnf 0.2.8 json file to make much more ez to look at it

### ISSUE THREAD

**Issue by Sanscode1937** [AngelDTF/FNF-NewgroundsPort#12]
[Funkin.txt](https://github.com/AngelDTF/FNF-NewgroundsPort/files/7942177/Funkin.txt)

**Comment by AngelWyvern** [comment]
I'm going to need more information on this.
This isn't a file that's in the repository, at least from what my searches tell me.
Are you asking me to modify a repository file, or modify something else to make my life easier?
If it is the latter, do note that I already have done what you suggested to speed up time and cause less confusion for myself.

**Comment by Sanscode1937** [comment]
oh 💀
