### ISSUE TITLE
Bug Report: Can't skip credits video in HTML5 target

### ISSUE THREAD

**Issue by Cheese-Curd** [AngelDTF/FNF-NewgroundsPort#13]
It replays after you press any accept button, if you spam enter fast enough you can go back to the main menu though

**Comment by AngelWyvern** [comment]
Noted. I’ll check tomorrow to see if I can replicate this bug once I fix my current wacky compiling problems that spews no useful info into the console.

**Comment by Cheese-Curd** [comment]
This is a little janky, I wonder if it was a one-off thing I haven't been able to recreate it, I'll keep the issue open just in case.

**Comment by AngelWyvern** [comment]
I haven't been able to replicate it myself either. I'm closing this issue as it is your request in DMs.
