### ISSUE TITLE
Enhancement: Animated actual cutscene

### ISSUE THREAD

**Issue by Sanscode1937** [AngelDTF/FNF-NewgroundsPort#15]
Can you add the animated actual cutscene like i do uhh like

https://user-images.githubusercontent.com/88786260/155856463-03ec2e44-7259-4790-882a-a1c72ac5ad89.mp4

**Comment by Cheese-Curd** [comment]
Angel will probably **not** add this as it's not in the source code of the game.

**Comment by AngelWyvern** [comment]
This project’s purpose is to make an accurate recreation via reverse engineering, therefore I’m only including what’s actually in the v0.2.8 Newgrounds Exclusive. The Newgrounds Exclusive does not contain real-time animated cutscene support. Enhancements like these belong in a sub-project.
