### ISSUE TITLE
Question: Add a comment

### ISSUE THREAD

**Issue by Sanscode1937** [AngelDTF/FNF-NewgroundsPort#16]
I found this comment on tank stage on ninjamuffin stream

						// this goes after tankSky and before tankMoutains in stage file
						// need to accomodate for the velocity thing!

can you just add it?

**Comment by Cheese-Curd** [comment]
I can't see why he wouldn't add a comment, but the code might have changed since the newgrounds release

**Comment by AngelWyvern** [comment]
Can you link me to the VOD of the stream and timestamp when it happened so I may see it for myself?

**Comment by Sanscode1937** [comment]
> Can you link me to the VOD of the stream and timestamp when it happened so I may see it for myself?

It on ninjamuffin coding a shader but full stream is gone

**Comment by Sanscode1937** [comment]
ok angel i found it
https://m.twitch.tv/ninja_muffin99/clip/ThirstyGoodMelonYouDontSay-JDt05LZzD1TGimnv

**Comment by Sanscode1937** [comment]
public function loadStage(name:String) {
		curStage = name;
	}

epic function

**Comment by AngelWyvern** [comment]
I would add it since there's documented proof, however this appears to be stuff added after v0.2.8. The order of the background assets is different than in the v0.2.8 javascript file, and the function loadStage isn't defined either. Thanks anyways.

![image](https://user-images.githubusercontent.com/43016525/157164805-3b639f12-2589-41c4-bc63-e4e05b797c7d.png)

**Comment by Sanscode1937** [comment]
> I would add it since there's documented proof, however this appears to be stuff added after v0.2.8. The order of the background assets is different than in the v0.2.8 javascript file, and the function loadStage isn't defined either. Thanks anyways.
> 
> ![image](https://user-images.githubusercontent.com/43016525/157164805-3b639f12-2589-41c4-bc63-e4e05b797c7d.png)

I know im just write it
