### ISSUE TITLE
Enhancement: Add a new FlxAnimate thingy

### ISSUE THREAD

**Issue by Cheemsandfriends** [AngelDTF/FNF-NewgroundsPort#19]
While looking into your repo, I saw that you had a very weird FlxAnimate and FlxSymbol.
(I know this is kinda some sort of spam but)
I've been working on a repo with a guy called [FlxAnimate](https://github.com/Dot-Stuff/flxanimate) which tries to support this.

Either way, the repo looks pretty good!
Really impressed

**Comment by AngelWyvern** [comment]
Hey, thanks for your interest! Issue #18 pointed me already to your repo, and I've already reused most of it for the project. It'll be out in the next commit. I apologize for the next commit taking so long, but by my estimations, I should be done within a week (give or take a few days), then the new code will be there. Thanks again!

**Comment by Cheemsandfriends** [comment]
Oh, didn't saw that issue!
I'm very sorry lol
I should close this up then.

**Comment by AngelWyvern** [comment]
It's no problem at all, lol. Have a good one.

**Comment by Cheemsandfriends** [comment]
Good!
I'll maybe took a look with the commit
Maybe there's something that may interest me to push it into the thing or some shit like that.

But at the moment, Have a great one :+1:
