### ISSUE TITLE
Enhancement: Game Build

### ISSUE THREAD

**Issue by Sanscode1937** [AngelDTF/FNF-NewgroundsPort#20]
Make download desktop build please I reset my pc and my all stuff is gone so

**Comment by AngelWyvern** [comment]
I’m going to need more information regarding the issue. There are downloads on the latest release for each platform I could build to, with both debug and release versions.

**Comment by Sanscode1937** [comment]
> I’m going to need more information regarding the issue. There are downloads on the latest release for each platform I could build to, with both debug and release versions.

Im just need downloadable build cause Idk im lazy or some shit and for another ppl

**Comment by Sanscode1937** [comment]
Im jst realize the game build already exist lol
