### ISSUE TITLE
can I use this as a base for my engine

### ISSUE THREAD

**Issue by Gothbr4dn** [AngelDTF/FNF-NewgroundsPort#21]
I am making a engine called otaku engine and I want to use this as a base for my engine.
I will credit you (if you say yes), but if you say no I won't use it and I will make my own version 
please and thank you

**Comment by Cheese-Curd** [comment]
I know the owner, so I would think he would say yes. I'm pretty sure he made it for others to make mods/new engines.

**Comment by br4dnblehh** [comment]
ok

**Comment by AngelWyvern** [comment]
Of course. I open sourced this to allow others to reuse it or build off of it. Good luck with your engine.

**Comment by br4dnblehh** [comment]
ok thanks I will make sure to credit you
