### ISSUE TITLE
Enhancement: Use hxCodec instead for compatibility on desktop

### ISSUE THREAD

**Issue by stilic** [AngelDTF/FNF-NewgroundsPort#22]
## What is your suggestion, and why should it be implemented?
There is a library called [hxCodec](https://github.com/polybiusproxy/hxCodec) which supports both web and desktop targets.
We should probably switch to this instead of using the current video code.

**Comment by AngelWyvern** [comment]
This is a port project to replicate FNF v0.2.8 as close as possible. I'm not aware of this being anywhere in the Newgrounds exclusive version. If you can find any evidence of this being in v0.2.8, please show me and I'll happily implement this. Otherwise, this will not be implemented.

**Comment by stilic** [comment]
> This is a port project to replicate FNF v0.2.8 as close as possible. I'm not aware of this being anywhere in the Newgrounds exclusive version. If you can find any evidence of this being in v0.2.8, please show me and I'll happily implement this. Otherwise, this will not be implemented.

The official Newgrounds version uses some custom code to play videos. But it is only designed to run on the HTML5 target if I remember. So, for make videos running on other targets, this may be a great idea to use a library.

Take for example FlxAnimate: you used this library instead of reverse-enginnering the custom code of the official web version of the game.

**Comment by AngelWyvern** [comment]
> The official Newgrounds version uses some custom code to play videos. But it is only designed to run on the HTML5 target if I remember. So, for make videos running on other targets, this may be a great idea to use a library.

Ninjamuffin made videos work via the OpenFL Video class (which, as you mentioned, only works on HTML targets), as can be seen [here](https://github.com/AngelDTF/FNF-NewgroundsPort/blob/remaster/source/FlxVideo.hx#L22).

> Take for example FlxAnimate: you used this library instead of reverse-enginnering the custom code of the official web version of the game.

I reverse-engineered FlxAnimate first, then copied some code over from the library just to make the code neater, not to update it. If you compare the code for [FlxSymbol from this repository](https://github.com/AngelDTF/FNF-NewgroundsPort/blob/remaster/source/animate/FlxSymbol.hx) to the [FlxAnim from the library's repository](https://github.com/Dot-Stuff/flxanimate/blob/master/flxanimate/animate/FlxAnim.hx) (it was renamed from FlxSymbol to FlxAnim), you'll see it's not exact, as v0.2.8 uses outdated code.

**Comment by stilic** [comment]
> Ninjamuffin made videos work via the OpenFL Video class (which, as you mentioned, only works on HTML targets), as can be seen [here](https://github.com/AngelDTF/FNF-NewgroundsPort/blob/remaster/source/FlxVideo.hx#L22).

Actually, hxCodec supports both HTML5 and desktop (not Mac, but we are waiting for the needed files). So, even if it is not part of the original FNF Newgrounds version, it would be just better to switch to the library, instead of using code that is only working on the web build of this port.

**Comment by AngelWyvern** [comment]
Thank you for your interest. This would be better suited for a fork of this project, as this is supposed to be as close to a 1:1 copy to the source content, therefore additional libraries will not be added into this project. I have had thoughts of making a v0.2.8+ version for general improvements and patches. If I ever get the inspiration to do it, I may include hxCodec and/or a newer version of the FlxAnimate library to fix the cutscenes.
