### ISSUE TITLE
Bug Report: Cant compile because of no Project.xml file, but its already there?

### ISSUE THREAD

**Issue by qq735-personal** [AngelDTF/FNF-NewgroundsPort#27]
![Screenshot 2022-06-21 134231](https://user-images.githubusercontent.com/49921877/174862837-f6eae4d2-812f-4d64-a140-a8715865bf22.png)
![Screenshot 2022-06-21 134245](https://user-images.githubusercontent.com/49921877/174862839-7ccf0853-84b5-4ae8-8362-7aa1542586fd.png)
I don't understand the issue here. can someone tell me whats wrong?

**Comment by qq735-personal** [comment]
im an idiot.
it was the wrong folder

**Comment by qq735-personal** [comment]
Now its just a bunch of stuff with poly mod thats not working im confused-
![Screenshot 2022-06-21 134721](https://user-images.githubusercontent.com/49921877/174863883-76ae4433-514f-4969-a875-e651ad28455e.png)

**Comment by AngelWyvern** [comment]
Try reinstalling polymod from either the default repo (`haxelib git polymod https://github.com/larsiusprime/polymod.git`), as some other engines use slightly modified polymod repos that may cause conflicts. If that doesn't work, you could also try reinstalling from my repo (`haxelib git polymod https://github.com/AngelDTF/haxe-polymod.git`), which uses a slightly older version of polymod with less bugs. If none of these work, you could also just choose to rip polymod entirely out of the project (by removing the references in `Project.xml` and `src/TitleState.hx`), as it doesn't really do much in it's current state.

**Comment by qq735-personal** [comment]
> Try reinstalling polymod from either the default repo (`haxelib git polymod https://github.com/larsiusprime/polymod.git`), as some other engines use slightly modified polymod repos that may cause conflicts. If that doesn't work, you could also try reinstalling from my repo (`haxelib git polymod https://github.com/AngelDTF/haxe-polymod.git`), which uses a slightly older version of polymod with less bugs. If none of these work, you could also just choose to rip polymod entirely out of the project (by removing the references in `Project.xml` and `src/TitleState.hx`), as it doesn't really do much in it's current state.

Thank you.

**Comment by qq735-personal** [comment]
> Try reinstalling polymod from either the default repo (`haxelib git polymod https://github.com/larsiusprime/polymod.git`), as some other engines use slightly modified polymod repos that may cause conflicts. If that doesn't work, you could also try reinstalling from my repo (`haxelib git polymod https://github.com/AngelDTF/haxe-polymod.git`), which uses a slightly older version of polymod with less bugs. If none of these work, you could also just choose to rip polymod entirely out of the project (by removing the references in `Project.xml` and `src/TitleState.hx`), as it doesn't really do much in it's current state.

it worked!
but now its just opened a web version of the game. Is that supposed to happen?

**Comment by AngelWyvern** [comment]
Change `lime test html5 -debug` to `lime test windows -debug`.

**Comment by qq735-personal** [comment]
> Change `lime test html5 -debug` to `lime test windows -debug`.

ok!
