### ISSUE TITLE
Bug Report: Free play menu does not replicate that of v0.2.8's

### ISSUE THREAD

**Issue by AngelWyvern** [AngelDTF/FNF-NewgroundsPort#3]
Upon opening the free play menu in v0.2.8, the screen is gray until the player is allowed to pick an option, then it goes into a bluish color as the first selected song is Tutorial. In the port, the screen just starts on the bluish color.

**Comment by AngelWyvern** [comment]
No longer an issue, I found out how to reverse engineer. See commit edde14140c7ef0ce9a9d5475b2a910a4b693954d.

**Comment by dummmmdum** [comment]
> No longer an issue, I found out how to reverse engineer. See commit edde14140c7ef0ce9a9d5475b2a910a4b693954d.

how?

**Comment by AngelWyvern** [comment]
> how?

This is gonna take a moment to explain.

Using Chrome's built in dev tools, I traced the JS file for the Friday Night Funkin' Newgrounds Exclusive version [(this is the file if you're curious)](https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/Funkin.js). I then used some extensions in VS Code and some case sensitive replacing to beautify this code and give some proper naming to the variables to make it easier to read. The end result wasn't the prettiest, but after a ton of trial and error and a lot of code comparisons between classes and functions that haven't changed, I basically self-taught myself how the compiler translates the Haxe code into Javascript, and used that knowledge to rewrite it back into Haxe. And just for some sanity checks, I could recompile my reverse engineered code back into Javascript and compare it to the compiled file for the Newgrounds Exclusive to make sure it matched. Using this knowledge, I tediously went through every class in the game and compared line by line to see what changed and what didn't to make this project. I didn't double check all of it though, so there may still be some mistranslations within my code, but for the most part, it's accurate, and it's v0.2.8.

**Comment by dummmmdum** [comment]
> > how?
> 
> This is gonna take a moment to explain.
> 
> Using Chrome's built in dev tools, I traced the JS file for the Friday Night Funkin' Newgrounds Exclusive version [(this is the file if you're curious)](https://uploads.ungrounded.net/alternate/1528000/1528775_alternate_113347_r88.zip/Funkin.js). I then used some extensions in VS Code and some case sensitive replacing to beautify this code and give some proper naming to the variables to make it easier to read. The end result wasn't the prettiest, but after a ton of trial and error and a lot of code comparisons between classes and functions that haven't changed, I basically self-taught myself how the compiler translates the Haxe code into Javascript, and used that knowledge to rewrite it back into Haxe. And just for some sanity checks, I could recompile my reverse engineered code back into Javascript and compare it to the compiled file for the Newgrounds Exclusive to make sure it matched. Using this knowledge, I tediously went through every class in the game and compared line by line to see what changed and what didn't to make this project. I didn't double check all of it though, so there may still be some mistranslations within my code, but for the most part, it's accurate, and it's v0.2.8.

i meant how you got the colors

**Comment by AngelWyvern** [comment]
If you’re asking how I found the color values, they were in the previously mentioned JS file, and then I converted them into the hexadecimal format as that was what Ninjamuffin was primarily using in the source code. 

If you’re asking how I fixed the bug, this was a bug related to the legacy version of my code, which wasn’t actually a reverse engineering and was more of a rewrite based on code from Psych Engine and FNF Modding Plus, and their implementations set the color on creation, while the official Newgrounds version sets the color continuously throughout the `update` function, and that function isn’t called until the state has fully transitioned. 

If I still haven’t answered your question exactly, my apologies but your question is a bit vague, in the future please specify more clearly what your question is.
