### ISSUE TITLE
Question: How To Compile FNF-NewgroundsPort(MACOS AND WINDOWS)(NOT A QUESTION)

### ISSUE THREAD

**Issue by JovadinoDev** [AngelDTF/FNF-NewgroundsPort#37]
I don't know where to contact the creator of this source code, i wanna contact him to put this tutorial on the code page. But i decided to put this as a question so macOS guys can know what to do! Windows users get outa here!!!!!! But windows users, if your having problems while compiling, I think this can help.

****Installing the Required Programs****

First you need to install Haxe and HaxeFlixel. I'm too lazy to write and keep updated with that setup (which is pretty simple).

[Install Haxe](https://haxe.org/download/) (If you're having issues installing libraries on latest, try using [Haxe 4.1.5](https://haxe.org/download/version/4.1.5/) instead)
[Install HaxeFlixel](https://haxeflixel.com/documentation/install-haxeflixel/) after downloading Haxe
Other installations you'd need is the additional libraries, a fully updated list will be in Project.xml in the project root. Currently, these are all of the things you need to install:

flixel
flixel-addons
flixel-ui
hscript
So for each of those type haxelib install [library] so shit like haxelib install flixel

This is the most important part of this thing for MacOS USERS!!!!! and i think windows users. (I think this can work with latest versions of macOS devices)

You HAVE to install and older version of flixel!! Install flixel first THEN do this part! If your having a error saying (UpdateFragment Something Something) you may need to read this, [Flixel 4.11.0](https://lib.haxe.org/p/flixel/4.11.0) I think 5.0.0 and other versions fucks it up so 4.11.0 is recommend!! Copy And Paste the installation on the link, then go to Terminal/Visual Studio Code to install 4.11.0 and it may work! For Visual Studio Code you need to close the window or force quit or just quit so it can work, wait in a maybe 10 or 20 seconds.and open visual studio again then it will WORK!!!! If it still doesn't work then your probably doing it wrong

You'll also need to install a couple things that involve Gits. To do this, you need to do a few things first.

Download [git-scm](https://git-scm.com/downloads). Works for Windows, Mac, and Linux, just select your build.
Follow instructions to install the application properly.
Run haxelib git polymod https://github.com/larsiusprime/polymod.git to install Polymod.
Run haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc to install Discord RPC.
At the moment, you can optionally fix some bugs regarding the engine:

A transition bug in songs with zoomed out cameras
Run haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons in the terminal/command-prompt.
A text rendering bug (mainly noticeable in the story menu under tracks)
Run haxelib git openfl https://github.com/openfl/openfl in the terminal/command-prompt.
You should have everything ready for compiling the game! Follow the guide below to continue!

**Compiling game**

Once you have all those installed, it's pretty easy to compile the game. You just need to run 'lime test html5 -debug' in the root of the project to build and run the HTML5 version. (command prompt navigation guide can be found here: https://ninjamuffin99.newgrounds.com/news/post/1090480)

To run it from your desktop (Windows, Mac, Linux) it can be a bit more involved. For Linux, you only need to open a terminal in the project directory and run 'lime test linux -debug' and then run the executable file in export/release/linux/bin. For MacOS you need to 'lime test mac -debug' on Visual Studio Code or Visual Studio(I use visual studio code so idk it will work for visual studio. For Windows, you need to install [Visual Studio Build Tools](https://visualstudio.microsoft.com/downloads/?q=Build+Tools) (you'll need to scroll down a bit to find the download). While installing, don't click on any of the options to install workloads. Instead, go to the individual components tab and choose the following:

MSVC C++ x64/x86 build tools (Tested with MSVC v143 - VS 2022 C++ x64/x86 build tools (v14.33-17.3))
Windows SDK (Tested with Windows 10 SDK (10.0.19041.0))
This will install about 4GB of crap, but once that is done you can open up a command line in the project's directory and run lime test windows -debug. Once that command finishes (it takes forever, even on a higher end PC, For Me(MacOS) doesn't take that long but if you have a slow computer, it may take forever!), you can run FNF from the .exe file under export\release\windows\bin As for Mac, 'lime test mac' <---- If your done with the source code if your not done or its not working GO BACK UP!!!!!! you'll find your .app build on 'export/release/macos/bin' I think thats all you need to know! Any typos i did or any stuff that is blank, comment!!! other wise you may be probably compiling.

**Comment by JovadinoDev** [comment]
If your having the same problems as the tutorial said, then do the same thing as macOS does. I think it should work!!

**Comment by Cheese-Curd** [comment]
The best way to contact the owner, is through this!
If this was a pull request, I'm sure Angel would take the edited `README` and add it to this repo.

**Comment by JovadinoDev** [comment]
mm ok thx

**Comment by AngelWyvern** [comment]
Now that I have (partial) access to a macOS machine, I'll have to do my own testing when I have time so I can update the README accordingly, thanks for bringing this to my attention.

**Comment by AngelWyvern** [comment]
I had to make a quick patch in `Main.hx` for one of the arguments removed from `FlxGame` in Flixel version 5.0.0, but after that, I was able to compile just fine with `lime test mac -debug` with Flixel version 5.2.1. I have yet to see an UpdateFragment error at all, to me it sounds like a corrupted Flixel installation, but I could be wrong.

**Comment by JovadinoDev** [comment]
kk
