### ISSUE TITLE
Bug Report: Cutscenes only work in browser

### ISSUE THREAD

**Issue by AngelWyvern** [AngelDTF/FNF-NewgroundsPort#4]
Due to the wacky ass way videos work in HaxeFlixel, cutscenes only work in the browser. This may be patched later with something that can play webm files on multiple platforms.

**Comment by AngelWyvern** [comment]
This repository has become more of a direct port rather than a recreation with patches, like it used to be. Therefore, I will not be fixing any bugs relating to v0.2.8 itself to keep it as close to the original game as possible.

**Comment by Cheese-Curd** [comment]
rip
