### ISSUE TITLE
Bug Report: Exiting out of preferences early crashes the game

### ISSUE THREAD

**Issue by AngelWyvern** [AngelDTF/FNF-NewgroundsPort#5]
If you go into the preferences menu, check/uncheck a checkbox, and exit the menu with ESC before the animation plays, you get a Null Reference Error crash.

**Comment by Cheese-Curd** [comment]
I found this accidentally lol

**Comment by AngelWyvern** [comment]
Fixed in commit 0fe3b0020819c91c9d16e548009f15905d87ed08. Thanks Cheese!
