### ISSUE TITLE
Question: i have a problem for dowload the source code.

### ISSUE THREAD

**Issue by ghost** [AngelDTF/FNF-NewgroundsPort#8]
When I download the source code, it downloads everything but many folders like source, example_mods and more

**Comment by Cheese-Curd** [comment]
That seems to be on your end, are you downloading it as a zip, or are you using Github Desktop?

**Comment by FrancescoPipino** [comment]
> That seems to be on your end, are you downloading it as a zip, or are you using Github Desktop?

**Comment by ghost** [comment]
Well I just downloaded the code.zip

**Comment by Cheese-Curd** [comment]
Did you go to the button that says **Code** then click **Download ZIP**? please give us more information.

**Comment by ghost** [comment]
Yes, I clicked on the code button and then I did .zip
Now I'm trying again in case I was stupid and I will be wrong to click

**Comment by ghost** [comment]
![h](https://user-images.githubusercontent.com/96877870/149340694-de9c5d56-9d63-4aaa-ab62-6469de945d44.png)

**Comment by ghost** [comment]
where is the others files????
I dowloaded the source code in .zip
Everybody can create a Google Drive link???

**Comment by AngelWyvern** [comment]
Could you try using something like GitHub Desktop or just regular Git to see if cloning works that way?
Also, I have no intentions of mirroring the code on other sites until the project is (at least mostly) finished.

**Comment by ghost** [comment]
ok it work thank you
